// Code generated by "stringer -type=Kind"; DO NOT EDIT.

package tui

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ModuleListKind-0]
	_ = x[WorkspaceListKind-1]
	_ = x[StateKind-2]
	_ = x[RunListKind-3]
	_ = x[RunKind-4]
	_ = x[TaskListKind-5]
	_ = x[TaskKind-6]
	_ = x[LogListKind-7]
	_ = x[LogKind-8]
}

const _Kind_name = "ModuleListKindWorkspaceListKindStateKindRunListKindRunKindTaskListKindTaskKindLogListKindLogKind"

var _Kind_index = [...]uint8{0, 14, 31, 40, 51, 58, 70, 78, 89, 96}

func (i Kind) String() string {
	if i < 0 || i >= Kind(len(_Kind_index)-1) {
		return "Kind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Kind_name[_Kind_index[i]:_Kind_index[i+1]]
}
