Output demos/modules.gif

Set Shell "bash"
Set FontSize 14
Set Width 1200
Set Height 600
Set Padding 10
Set Framerate 24

Hide
Type "hacks/reset_demo.sh" Enter
Type "go run main.go -w demos" Enter
Sleep 0.5s
Show

Sleep 2s

Ctrl+a Sleep 2s Type "i" Sleep 3s
Type "T" Sleep 3s Enter Sleep 3s
Type "M"
Ctrl+a Sleep 1s Type "f" Sleep 2s
Ctrl+a Sleep 1s Type "v" Sleep 2s
Type "T" Sleep 2s Enter Sleep 3s
